project_id = "wcienwozdurwhswaarjy"

[functions.join-couple-space]
verify_jwt = false

[functions.create-couple-space]
verify_jwt = false

[functions.activate-session]
verify_jwt = false

[functions.update-step-completion]
verify_jwt = false

[functions.leave-couple-space]
verify_jwt = false

[functions.leave-and-create-new-space]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.get-analytics]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
