project_id = "wcienwozdurwhswaarjy"

[functions.join-couple-space]
verify_jwt = false

[functions.create-couple-space]
verify_jwt = false

[functions.activate-session]
verify_jwt = false

[functions.update-step-completion]
verify_jwt = false

[functions.leave-couple-space]
verify_jwt = false
